services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["/app/.venv/bin/fastapi", "dev", "src/main.py", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend/src:/app/src
    develop:
      watch:
        - action: rebuild
          path: backend/project.toml
        - action: restart
          path: backend/src
